### ISSUE TITLE
portal:SiteLogo not rendering svg graphics in version 2.7.0.0

### ISSUE THREAD

**Issue by joedavis01** [i7MEDIA/mojoportal#101]
I am using v2.7.0.0 with sql server and the portal:SiteLogo  control is not rendering svg graphics. 

Here is what the portal:SiteLogo renders
`<a href="/" title="Angler Nation" class="site-logo"><img class="site-logo-img" alt="Angler Nation" src="/Data/Sites/1/logos/logo.svg"></a>`

If I remove the anchor element and use the following markup svg is rendered
`<img src="/Data/Sites/1/logos/logo.svg"  alt="Site Logo">`

It seems as though svg graphics cannot be used inside an anchor element and must be rendered using an SVG element instead?

**Comment by joedavis01** [comment]
I am modifying the **SiteLogo** control to render svg element on svg logo type as follows
`<svg>
    <a href="/"><image href="/Data/Sites/1/logos/logo.svg" image=""></image></a>
</svg>`

This works on my dev machine. I just need to figure out how to change the cursor to hand or finger on hover.

**Comment by Isaac-Hall** [comment]
Hi Joe,

Your logo.svg will likely render just fine if a width and height are set on the img tag. In the past, I have also solved this problem by making sure the SVG was exported correctly from illustrator, and by adding CSS to set min-widths / min-heights on the logo. For your own skin, setting a min-width and min-height with the correct dimensions for your logo is the easy solution. 

I have been looking for a good solution that will allow all kinds of aspect ratios on logos to work, and allow the responsive box to be checked when exporting, that way we can fix this in Framework without it breaking anyone's logo dimensions. I am not sure what changes between the rendering of an <svg> element with an xlink anchor / image in it and an <a> with an img with svg source in it - but it may be a possible solution as long as we can detect that the selected sitelogo has the .svg extension and then render the proper markup. It's worth looking into anyway, so thanks for the suggestion!

Hope this helps.

**Comment by Isaac-Hall** [comment]
Some followup information:

IF you ensure that you export your .svg with a viewBox set, then you can set a relative width on the wrapping <a> (site-logo class in your example) and the .svg should scale while maintaining the aspect ratio set in the viewBox.
If you ensure that you do not export from illustrator with the "responsive" checkbox checked, the svg should maintain the dimensions it was exported at.
Another reason why some people get "blank" .svg files is that they have have an image element in the svg rather than actual vectors, but exported with the "link" option instead of "embed". You need to make sure that your image is embedded and not linked when exporting.
Internet Explorer will properly scale the image space taken up by an <a> with .svg src, but will not actually scale the drawing.

Hope this helps.
