### ISSUE TITLE
Shared Files: Upload Error

### ISSUE THREAD

**Issue by joseph-fowler** [i7MEDIA/mojoportal#160]
Administration Menu -> Content Manager -> Shared Files [Folder]:
Unable to upload files, log gives error "mojoPortal.Web.UI.BaseContentUploadHandler - User has no edit permission so returning 404"

**Comment by JosephMDavis** [comment]
Most modules in mojo are not meant to be edited from the Content Manager. The Content Manager is really designed to publish modules on multiple pages and for finding modules that have been removed from pages. It can also be used to schedule publishing of modules.

In this case, the Shared Files module isn't allowing upload because it's not being used in context of a page, as it is designed to be used.

I'm closing this as "won't fix" for now because it's very low priority and the work around is to use the module from a page.
